import { initPreferences } from '@vben/preferences';
await initPreferences({ namespace: 'dict-disposable-preview' });
const { createApp, defineComponent, h } = await import('vue');
const { createRouter, createWebHistory, RouterView } = await import('vue-router');
const { registerAccessDirective } = await import('@vben/access');
const { registerLoadingDirective } = await import('@vben/common-ui');
const { providePluginsOptions } = await import('@vben/plugins');
const { initStores, useAccessStore } = await import('@vben/stores');
const { initComponentAdapter } = await import('#/adapter/component');
const { initSetupVbenForm, useVbenForm } = await import('#/adapter/form');
const { setupI18n } = await import('#/locales');
await import('@vben/styles');
await import('@vben/styles/antdv-next');
await initComponentAdapter();
await initSetupVbenForm();
providePluginsOptions({ form: { useVbenForm } });
const { default: List } = await import('#/views/system/dict/list.vue');
const router = createRouter({ history: createWebHistory(), routes: [{ path: '/:pathMatch(.*)*', component: List }] });
const app = createApp(defineComponent(() => () => h(RouterView)));
registerLoadingDirective(app, { loading: 'loading', spinning: 'spinning' });
await setupI18n(app);
await initStores(app, { namespace: 'dict-disposable-preview' });
const access = useAccessStore();
access.setAccessToken('dict-preview');
access.setAccessCodes(['system:dict:list', 'system:dict:create', 'system:dict:update', 'system:dict:delete']);
registerAccessDirective(app);
app.use(router);
const { VueQueryPlugin } = await import('@tanstack/vue-query');
app.use(VueQueryPlugin);
app.mount('#app');
const { unmountGlobalLoading } = await import('@vben/utils');
unmountGlobalLoading();
